# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anagram_solver.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(450, 600))
        MainWindow.setMaximumSize(QtCore.QSize(450, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 412, 551))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.MainLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.MainLayout.setContentsMargins(0, 0, 0, 0)
        self.MainLayout.setObjectName("MainLayout")
        self.SettingsLayout1 = QtWidgets.QHBoxLayout()
        self.SettingsLayout1.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.SettingsLayout1.setObjectName("SettingsLayout1")
        self.TextInputLabels = QtWidgets.QVBoxLayout()
        self.TextInputLabels.setObjectName("TextInputLabels")
        self.InputStringText = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputStringText.sizePolicy().hasHeightForWidth())
        self.InputStringText.setSizePolicy(sizePolicy)
        self.InputStringText.setMinimumSize(QtCore.QSize(0, 30))
        self.InputStringText.setMaximumSize(QtCore.QSize(100, 30))
        self.InputStringText.setObjectName("InputStringText")
        self.TextInputLabels.addWidget(self.InputStringText)
        self.RequiredWordsText = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RequiredWordsText.sizePolicy().hasHeightForWidth())
        self.RequiredWordsText.setSizePolicy(sizePolicy)
        self.RequiredWordsText.setMinimumSize(QtCore.QSize(0, 30))
        self.RequiredWordsText.setMaximumSize(QtCore.QSize(100, 30))
        self.RequiredWordsText.setObjectName("RequiredWordsText")
        self.TextInputLabels.addWidget(self.RequiredWordsText)
        self.SettingsLayout1.addLayout(self.TextInputLabels)
        self.TextInputBoxes = QtWidgets.QVBoxLayout()
        self.TextInputBoxes.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.TextInputBoxes.setObjectName("TextInputBoxes")
        self.InputString = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputString.sizePolicy().hasHeightForWidth())
        self.InputString.setSizePolicy(sizePolicy)
        self.InputString.setMinimumSize(QtCore.QSize(300, 30))
        self.InputString.setMaximumSize(QtCore.QSize(16777215, 30))
        self.InputString.setObjectName("InputString")
        self.TextInputBoxes.addWidget(self.InputString)
        self.RequiredWords = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RequiredWords.sizePolicy().hasHeightForWidth())
        self.RequiredWords.setSizePolicy(sizePolicy)
        self.RequiredWords.setMinimumSize(QtCore.QSize(300, 30))
        self.RequiredWords.setMaximumSize(QtCore.QSize(16777215, 30))
        self.RequiredWords.setPlainText("")
        self.RequiredWords.setObjectName("RequiredWords")
        self.TextInputBoxes.addWidget(self.RequiredWords)
        self.SettingsLayout1.addLayout(self.TextInputBoxes)
        self.MainLayout.addLayout(self.SettingsLayout1)
        self.SettingsLayout2 = QtWidgets.QHBoxLayout()
        self.SettingsLayout2.setObjectName("SettingsLayout2")
        self.MinLengthText = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MinLengthText.sizePolicy().hasHeightForWidth())
        self.MinLengthText.setSizePolicy(sizePolicy)
        self.MinLengthText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.MinLengthText.setObjectName("MinLengthText")
        self.SettingsLayout2.addWidget(self.MinLengthText)
        self.MinValue = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.MinValue.setMaximumSize(QtCore.QSize(16777215, 25))
        self.MinValue.setEditable(False)
        self.MinValue.setObjectName("MinValue")
        self.MinValue.addItem("")
        self.MinValue.addItem("")
        self.MinValue.addItem("")
        self.MinValue.addItem("")
        self.MinValue.addItem("")
        self.MinValue.addItem("")
        self.MinValue.addItem("")
        self.MinValue.addItem("")
        self.MinValue.addItem("")
        self.MinValue.addItem("")
        self.SettingsLayout2.addWidget(self.MinValue)
        self.MaxLengthText = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MaxLengthText.sizePolicy().hasHeightForWidth())
        self.MaxLengthText.setSizePolicy(sizePolicy)
        self.MaxLengthText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.MaxLengthText.setObjectName("MaxLengthText")
        self.SettingsLayout2.addWidget(self.MaxLengthText)
        self.MaxValue = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.MaxValue.setMaximumSize(QtCore.QSize(16777215, 25))
        self.MaxValue.setObjectName("MaxValue")
        self.MaxValue.addItem("")
        self.MaxValue.addItem("")
        self.MaxValue.addItem("")
        self.MaxValue.addItem("")
        self.MaxValue.addItem("")
        self.MaxValue.addItem("")
        self.MaxValue.addItem("")
        self.MaxValue.addItem("")
        self.MaxValue.addItem("")
        self.MaxValue.addItem("")
        self.SettingsLayout2.addWidget(self.MaxValue)
        self.MainLayout.addLayout(self.SettingsLayout2)
        self.SolveButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.SolveButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.SolveButton.setObjectName("SolveButton")
        self.MainLayout.addWidget(self.SolveButton)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.MainLayout.addItem(spacerItem)
        self.OutputList = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutputList.sizePolicy().hasHeightForWidth())
        self.OutputList.setSizePolicy(sizePolicy)
        self.OutputList.setMinimumSize(QtCore.QSize(0, 350))
        self.OutputList.setMaximumSize(QtCore.QSize(16777215, 380))
        self.OutputList.setObjectName("OutputList")
        self.MainLayout.addWidget(self.OutputList)
        self.ProgressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget_3)
        self.ProgressBar.setProperty("value", 0)
        self.ProgressBar.setObjectName("ProgressBar")
        self.MainLayout.addWidget(self.ProgressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionReset)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.InputStringText.setText(_translate("MainWindow", "Input String:"))
        self.RequiredWordsText.setText(_translate("MainWindow", "Required Words:"))
        self.MinLengthText.setText(_translate("MainWindow", "Min Word Length:"))
        self.MinValue.setItemText(0, _translate("MainWindow", "(none)"))
        self.MinValue.setItemText(1, _translate("MainWindow", "2"))
        self.MinValue.setItemText(2, _translate("MainWindow", "3"))
        self.MinValue.setItemText(3, _translate("MainWindow", "4"))
        self.MinValue.setItemText(4, _translate("MainWindow", "5"))
        self.MinValue.setItemText(5, _translate("MainWindow", "6"))
        self.MinValue.setItemText(6, _translate("MainWindow", "7"))
        self.MinValue.setItemText(7, _translate("MainWindow", "8"))
        self.MinValue.setItemText(8, _translate("MainWindow", "9"))
        self.MinValue.setItemText(9, _translate("MainWindow", "10"))
        self.MaxLengthText.setText(_translate("MainWindow", "Max Word Length:"))
        self.MaxValue.setItemText(0, _translate("MainWindow", "(none)"))
        self.MaxValue.setItemText(1, _translate("MainWindow", "2"))
        self.MaxValue.setItemText(2, _translate("MainWindow", "3"))
        self.MaxValue.setItemText(3, _translate("MainWindow", "4"))
        self.MaxValue.setItemText(4, _translate("MainWindow", "5"))
        self.MaxValue.setItemText(5, _translate("MainWindow", "6"))
        self.MaxValue.setItemText(6, _translate("MainWindow", "7"))
        self.MaxValue.setItemText(7, _translate("MainWindow", "8"))
        self.MaxValue.setItemText(8, _translate("MainWindow", "9"))
        self.MaxValue.setItemText(9, _translate("MainWindow", "10"))
        self.SolveButton.setText(_translate("MainWindow", "SOLVE"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About Anagram Solver"))

